%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ue3.iPhone_CompileServerName" "10.235.2.125"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ue3.iPhone_SigningServerName" "10.235.2.125"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ue3.iPhone_SdkVersion" "7.1"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ue3.iPhone_DeveloperSigningIdentity" "iPhone Developer: Xia Wentao (4K4VT2UX58)"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ue3.iPhone_DistributionSigningIdentity" "iPhone Developer: Xia Wentao (4K4VT2UX58)"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ue3.iPhone_DistributionSigningIdentity iPhone Distribution" " Westhouse Corporation Limited"

%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ANDROID_ROOT" "D:\Android"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ANDROID_HOME" "D:\Android\android-sdk"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ANDROID_NDK" "D:\Android\android-ndk-r9-windows-x86\android-ndk-r9"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ANROID_SDK_HOME" "D:\Android\android-sdk"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "NDKROOT" "D:\Android\android-ndk-r9-windows-x86\android-ndk-r9"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ANT_HOME" "D:\Android\apache-ant-1.9.2"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "ANT_ROOT" "D:\Android\apache-ant-1.9.2"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "CYGWIN_HOME" "D:\Android\cygwin"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "JAVA_HOME" "D:\Android\jdk1.7.0_05"
%kukuhero_HOME%/CMakeModules/bin/SetEnvironment.exe "Path" "%Path%;D:\Android\android-sdk\platform-tools"