;"Hello, World!"
;(string #\h #\e #\l #\l #\o)
;(define greeting "Hello; Hello!")
;(string-ref greeting 0)
;(string-append "E "
;               "Pluribus "
;               "Unum")
;(define a-3-char-long-string (make-string 3))
;a-3-char-long-string
;(define hello (string #\H #\e #\l #\l #\o)) 
;hello
;(string-set! hello 1 #\a)
;hello
;(vector 0 1 2 3 4)
;(define v (make-vector 5))
;v
;(cons 1 #t)
;'(1 . #t)
;(define x (cons 1 #t))
;(car x)
;(cdr x)
;(set-car! x 2)
;(set-cdr! x #f)
;x
;(define y (cons (cons 1 2) 3))
;y
;(car (car y))
;(cdr (car y))
;(caar y)
;(cdar y)
;(cons 1 (cons 2 (cons 3 (cons 4 5))))
;'()
;`(1 . (2 . (3 . (4 . ()))))
;(list 1 2 3 4)
;'(1 2 3 4)
;
;(define y (list 1 2 3 4))
;(list-ref y 0) 
;(list-ref y 3) 
;(list-tail y 1) 
;(list-tail y 3) 
;(pair? '(1 . 2)) 
;(pair? '(1 2))   
;(pair? '())      
;(list? '())      
;(null? '())      
(list? '(1 2))   
(list? '(1 . 2)) 
(null? '(1 2))   
(null? '(1 . 2)) 
(char->integer #\d) 
(integer->char 50)  
(string->list "hello")
(number->string 16)
(string->number "16")
(string->number "Am I a hot number?")
(string->number "16" 8)
(symbol->string 'symbol)
(string->symbol "string")
