cl /clr abstract_sealed.cpp
cl /clr checking_casts.cpp
cl /clr constructor_inheritance.cpp
cl /clr constructor_order.cpp
cl /clr destructors_and_inheritance.cpp
cl /clr explicit_override.cpp
cl /clr finalizers_and_inheritance.cpp
cl /clr native_managed_virtual.cpp
cl /clr new_method.cpp
cl /clr override.cpp
cl /clr virtual_properties2.cpp