cl /clr arraylist.cpp
cl /clr arrays_copy.cpp
cl /clr arrays_foreach.cpp
cl /clr arrays_initializing.cpp
cl /clr arrays_initializing2.cpp
cl /clr arrays_interior_ptr.cpp
cl /clr arrays_iterators.cpp
cl /clr arrays_length.cpp
cl /clr arrays_managed_native_comparison.cpp
cl /clr arrays_nondefault_ctor.cpp
cl /clr arrays_parameter.cpp
cl /clr arrays_sort_search.cpp
cl /clr arrays_uninitialized_elements.cpp
cl /clr array_dimension_type.cpp
cl /clr array_equality_test.cpp
cl /clr array_exception.cpp
cl /clr cli_printf.cpp
cl /clr convert_and_parse.cpp
cl /clr enum.cpp
cl /clr enum_flags.cpp
cl /clr enum_format.cpp
cl /clr enum_format2.cpp
cl /clr enum_type_specified.cpp
cl /clr exception_message.cpp
cl /clr list_generic.cpp
cl /clr managed_multidimensional_array_as_parameter.cpp
cl /clr param_array.cpp
cl /clr stream_writer_reader.cpp
cl /clr stringbuilder.cpp
cl /clr stringwriter.cpp
cl /clr string_alignment_specifier.cpp
cl /clr string_compare.cpp
cl /clr string_equality.cpp
cl /clr string_foreach.cpp
cl /clr string_numerical_formatting.cpp
cl /clr string_operator_plus.cpp
cl /clr string_tochararray.cpp
cl /clr string_wcout.cpp
cl /clr to_upper.cpp
cl /clr writeline.cpp