if(CMAKE_CXX_FLAGS_DEBUG MATCHES "/RTC1")
   string(REPLACE "/RTC1" " " CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
endif()

if(CMAKE_CXX_FLAGS MATCHES "/EHsc")
   string(REPLACE "/EHsc" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
endif()

macro(add_executable_clr cppname)
    add_executable(${cppname} ${ARGN})
    set_target_properties(${cppname} PROPERTIES VS_DOTNET_REFERENCES "System;System.Core;System.Data;System.Drawing;System.Xml")
    set_target_properties(${cppname} PROPERTIES COMPILE_FLAGS "/clr /EHa")
endmacro()

macro(add_library_clr cppname)
    add_library(${cppname} SHARED ${ARGN})
    set_target_properties(${cppname} PROPERTIES VS_DOTNET_REFERENCES "System;System.Core;System.Data;System.Drawing;System.Xml")
    set_target_properties(${cppname} PROPERTIES COMPILE_FLAGS "/clr /EHa")
    set_target_properties(${cppname} PROPERTIES LINKER_LANGUAGE CXX)
endmacro()