cl /clr debug_print.cpp
cl /clr unboxing.cpp
cl /clr auto_handle.cpp
cl /clr parameter_passing.cpp
cl /clr pass_by_value.cpp
cl /clr pass_by_ref.cpp
cl /clr pass_by_ref2.cpp
cl /clr pass_by_ref3.cpp
cl /clr handle_to_valuetype.cpp
cl /clr valuetype_trackingref.cpp
cl /clr return_values.cpp