;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-advanced-reader.ss" "lang")((modname |2.1|) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #t #t none #f ())))
(boolean? #t)
(boolean? "Hello, World!")
(not #f)
(not #t)
(number? 42)
(number? #t)
(complex? 2+3i)
(real? 2+3i)
(real? 3.1416)
(real? 22/7)
(real? 42)
(rational? 2+3i)
(rational? 3.1416)
(rational? 22/7)
(integer? 22/7)
(integer? 42)
(eqv? 42 42)
(eqv? 42 #f)
(eqv? 42 42.0)
(= 42 42)
(= 42 42.0)
(< 3 2)
(>= 4.5 3)
(+ 1 2 3)
(- 5.3 2)
(- 5 2 1)
(* 1 2 3)
(/ 6 3)
(/ 22 7)
(expt 2 3)
(expt 4 1/2)
(- 4)
(/ 4)
(max 1 3 4 2 3)
(min 1 3 4 2 3)
(abs  3)
(abs -4)
(char? #\c)
(char? 1)
(char? #\;)
(char=? #\a #\a)
(char<? #\a #\b)
(char>=? #\a #\b)
(char-ci=? #\a #\A)
(char-ci<? #\a #\B)
(char-downcase #\A)
(char-upcase #\a)
#t
42
#\c
(quote xyz)
'E
(symbol? 'xyz)
(symbol? 42)
(eqv? 'Calorie 'calorie)
(define xyz 9)
xyz
(set! xyz #\c)
xyz
