cl /clr cards_main.cpp
cl /clr generic_method_on_stlclr_collection.cpp
cl /clr interface_method_on_stlclr_collection.cpp
cl /clr interface_method_on_stlclr_container.cpp
cl /clr stlclr_algorithm_on_net_collection.cpp
cl /clr stlclr_convert_from_net_to_stlclr.cpp
cl /clr stlclr_custom_functor.cpp
cl /clr stlclr_functor.cpp
cl /clr stlclr_functor_delegate.cpp
cl /clr stlclr_functor_delegate_generic.cpp
cl /clr stlclr_iterator.cpp
cl /clr stlclr_make_collection.cpp
cl /clr stlclr_make_vector.cpp
cl /clr stlclr_reverse_generic.cpp
cl /clr stlclr_reverse_vector.cpp
cl /clr:safe /LD stlclr_vector_assembly1.cpp
cl /clr stlclr_vector_assembly2.cpp
cl /clr stlclr_vector_ilist.cpp
cl /clr stl_simple1.cpp
cl /clr stl_simple2.cpp
cl /clr stl_simple3.cpp
cl /clr Taxonomy.cpp