((lambda (x) (+ x 2)) 5)
(define add2
  (lambda (x) (+ x 2)))
(add2 4)
(add2 9)
(define x '(1 2 3))
(apply + x)
(apply + 1 2 3 x)
(define display3
  (lambda (arg1 arg2 arg3)
    (display arg1)
    (display " ")
    (display arg2)
    (display " ")
    (display arg3)
    (newline)))
(display3 "hehe" "nimei" "a")
